name: fabricationdesign
favicon: null
layout_spectrum: 0.9267482636496425
typography_spectrum: 0.41785105178132653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.03060793597251177
  lightness: 0.7224760325625539
  saturation: 0.19921330688521266
  rhythmicContrast: 0.8377155482303351
purpose: []
